[2024-04-29T12:14:03.825+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_metrics.publish.customer_metrics_run scheduled__2024-04-28T00:00:00+00:00 [queued]>
[2024-04-29T12:14:03.831+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_metrics.publish.customer_metrics_run scheduled__2024-04-28T00:00:00+00:00 [queued]>
[2024-04-29T12:14:03.832+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-29T12:14:03.843+0000] {taskinstance.py:2214} INFO - Executing <Task(DbtRunLocalOperator): publish.customer_metrics_run> on 2024-04-28 00:00:00+00:00
[2024-04-29T12:14:03.849+0000] {standard_task_runner.py:60} INFO - Started process 3766 to run task
[2024-04-29T12:14:03.851+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'customer_metrics', 'publish.customer_metrics_run', 'scheduled__2024-04-28T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/customer_metrics.py', '--cfg-path', '/tmp/tmpz2lt3fb3']
[2024-04-29T12:14:03.853+0000] {standard_task_runner.py:88} INFO - Job 19: Subtask publish.customer_metrics_run
[2024-04-29T12:14:03.889+0000] {task_command.py:423} INFO - Running <TaskInstance: customer_metrics.publish.customer_metrics_run scheduled__2024-04-28T00:00:00+00:00 [running]> on host 925dffa277c3
[2024-04-29T12:14:03.944+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='customer_metrics' AIRFLOW_CTX_TASK_ID='publish.customer_metrics_run' AIRFLOW_CTX_EXECUTION_DATE='2024-04-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-28T00:00:00+00:00'
[2024-04-29T12:14:03.945+0000] {local.py:202} INFO - Cloning project to writable temp directory /tmp/tmp84_tv93q from /opt/airflow/include/dbt/fraud
[2024-04-29T12:14:03.948+0000] {config.py:253} INFO - Using user-supplied profiles.yml at /opt/airflow/include/dbt/fraud/profiles.yml
[2024-04-29T12:14:03.948+0000] {local.py:235} INFO - Trying to run the command:
 ['/home/airflow/.local/bin/dbt', 'run', '--models', 'customer_metrics', '--profiles-dir', '/opt/airflow/include/dbt/fraud', '--profile', 'fraud', '--target', 'dev']
From /tmp/tmp84_tv93q
[2024-04-29T12:14:03.949+0000] {local.py:236} INFO - Using environment variables keys: dict_keys(['AIRFLOW_CTX_DAG_OWNER', 'AIRFLOW_CTX_DAG_ID', 'AIRFLOW_CTX_TASK_ID', 'AIRFLOW_CTX_EXECUTION_DATE', 'AIRFLOW_CTX_TRY_NUMBER', 'AIRFLOW_CTX_DAG_RUN_ID'])
[2024-04-29T12:14:03.949+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-04-29T12:14:03.950+0000] {subprocess.py:73} INFO - Running command: ['/home/airflow/.local/bin/dbt', 'run', '--models', 'customer_metrics', '--profiles-dir', '/opt/airflow/include/dbt/fraud', '--profile', 'fraud', '--target', 'dev']
[2024-04-29T12:14:03.959+0000] {subprocess.py:84} INFO - Command output:
[2024-04-29T12:14:05.746+0000] {subprocess.py:94} INFO - [0m12:14:05  Running with dbt=1.7.13
[2024-04-29T12:14:06.666+0000] {subprocess.py:94} INFO - [0m12:14:06  Registered adapter: snowflake=1.7.3
[2024-04-29T12:14:06.683+0000] {subprocess.py:94} INFO - [0m12:14:06  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2024-04-29T12:14:07.721+0000] {subprocess.py:94} INFO - [0m12:14:07  Found 3 models, 0 sources, 0 exposures, 0 metrics, 430 macros, 0 groups, 0 semantic models
[2024-04-29T12:14:07.722+0000] {subprocess.py:94} INFO - [0m12:14:07
[2024-04-29T12:14:09.384+0000] {subprocess.py:94} INFO - [0m12:14:09  Concurrency: 1 threads (target='dev')
[2024-04-29T12:14:09.384+0000] {subprocess.py:94} INFO - [0m12:14:09
[2024-04-29T12:14:09.396+0000] {subprocess.py:94} INFO - [0m12:14:09  1 of 1 START sql table model prod.customer_metrics ............................. [RUN]
[2024-04-29T12:14:09.988+0000] {subprocess.py:94} INFO - [0m12:14:09  1 of 1 ERROR creating sql table model prod.customer_metrics .................... [[31mERROR[0m in 0.59s]
[2024-04-29T12:14:09.990+0000] {subprocess.py:94} INFO - [0m12:14:09
[2024-04-29T12:14:09.991+0000] {subprocess.py:94} INFO - [0m12:14:09  Finished running 1 table model in 0 hours 0 minutes and 2.27 seconds (2.27s).
[2024-04-29T12:14:09.999+0000] {subprocess.py:94} INFO - [0m12:14:09
[2024-04-29T12:14:10.000+0000] {subprocess.py:94} INFO - [0m12:14:09  [31mCompleted with 1 error and 0 warnings:[0m
[2024-04-29T12:14:10.000+0000] {subprocess.py:94} INFO - [0m12:14:10
[2024-04-29T12:14:10.001+0000] {subprocess.py:94} INFO - [0m12:14:10    Database Error in model customer_metrics (models/customer_metrics.sql)
[2024-04-29T12:14:10.001+0000] {subprocess.py:94} INFO -   001003 (42000): SQL compilation error:
[2024-04-29T12:14:10.002+0000] {subprocess.py:94} INFO -   syntax error line 20 at position 24 unexpected ';'.
[2024-04-29T12:14:10.002+0000] {subprocess.py:94} INFO -   compiled Code at target/run/fraud/models/customer_metrics.sql
[2024-04-29T12:14:10.002+0000] {subprocess.py:94} INFO - [0m12:14:10
[2024-04-29T12:14:10.003+0000] {subprocess.py:94} INFO - [0m12:14:10  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2024-04-29T12:14:10.587+0000] {subprocess.py:98} INFO - Command exited with return code 1
[2024-04-29T12:14:10.596+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v11.json is above dbt-ol supported version 7. This might cause errors.
[2024-04-29T12:14:10.602+0000] {local.py:252} INFO - Inlets: []
[2024-04-29T12:14:10.602+0000] {local.py:253} INFO - Outlets: []
[2024-04-29T12:14:10.603+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-29T12:14:10.621+0000] {dag.py:3834} INFO - Setting next_dagrun for customer_metrics to 2024-04-29 00:00:00+00:00, run_after=2024-04-30 00:00:00+00:00
[2024-04-29T12:14:10.648+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/base.py", line 246, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 370, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 257, in run_command
    self.exception_handling(result)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 136, in exception_handling
    raise AirflowException(
airflow.exceptions.AirflowException: ('dbt command failed. The command returned a non-zero exit code 1. Details: ', '\x1b[0m12:14:05  Running with dbt=1.7.13', '\x1b[0m12:14:06  Registered adapter: snowflake=1.7.3', '\x1b[0m12:14:06  Unable to do partial parsing because saved manifest not found. Starting full parse.', '\x1b[0m12:14:07  Found 3 models, 0 sources, 0 exposures, 0 metrics, 430 macros, 0 groups, 0 semantic models', '\x1b[0m12:14:07', "\x1b[0m12:14:09  Concurrency: 1 threads (target='dev')", '\x1b[0m12:14:09', '\x1b[0m12:14:09  1 of 1 START sql table model prod.customer_metrics ............................. [RUN]', '\x1b[0m12:14:09  1 of 1 ERROR creating sql table model prod.customer_metrics .................... [\x1b[31mERROR\x1b[0m in 0.59s]', '\x1b[0m12:14:09', '\x1b[0m12:14:09  Finished running 1 table model in 0 hours 0 minutes and 2.27 seconds (2.27s).', '\x1b[0m12:14:09', '\x1b[0m12:14:09  \x1b[31mCompleted with 1 error and 0 warnings:\x1b[0m', '\x1b[0m12:14:10', '\x1b[0m12:14:10    Database Error in model customer_metrics (models/customer_metrics.sql)', '  001003 (42000): SQL compilation error:', "  syntax error line 20 at position 24 unexpected ';'.", '  compiled Code at target/run/fraud/models/customer_metrics.sql', '\x1b[0m12:14:10', '\x1b[0m12:14:10  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1')
[2024-04-29T12:14:10.651+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=customer_metrics, task_id=publish.customer_metrics_run, execution_date=20240428T000000, start_date=20240429T121403, end_date=20240429T121410
[2024-04-29T12:14:10.663+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 19 for task publish.customer_metrics_run (('dbt command failed. The command returned a non-zero exit code 1. Details: ', '\x1b[0m12:14:05  Running with dbt=1.7.13', '\x1b[0m12:14:06  Registered adapter: snowflake=1.7.3', '\x1b[0m12:14:06  Unable to do partial parsing because saved manifest not found. Starting full parse.', '\x1b[0m12:14:07  Found 3 models, 0 sources, 0 exposures, 0 metrics, 430 macros, 0 groups, 0 semantic models', '\x1b[0m12:14:07', "\x1b[0m12:14:09  Concurrency: 1 threads (target='dev')", '\x1b[0m12:14:09', '\x1b[0m12:14:09  1 of 1 START sql table model prod.customer_metrics ............................. [RUN]', '\x1b[0m12:14:09  1 of 1 ERROR creating sql table model prod.customer_metrics .................... [\x1b[31mERROR\x1b[0m in 0.59s]', '\x1b[0m12:14:09', '\x1b[0m12:14:09  Finished running 1 table model in 0 hours 0 minutes and 2.27 seconds (2.27s).', '\x1b[0m12:14:09', '\x1b[0m12:14:09  \x1b[31mCompleted with 1 error and 0 warnings:\x1b[0m', '\x1b[0m12:14:10', '\x1b[0m12:14:10    Database Error in model customer_metrics (models/customer_metrics.sql)', '  001003 (42000): SQL compilation error:', "  syntax error line 20 at position 24 unexpected ';'.", '  compiled Code at target/run/fraud/models/customer_metrics.sql', '\x1b[0m12:14:10', '\x1b[0m12:14:10  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1'); 3766)
[2024-04-29T12:14:10.672+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-29T12:14:10.686+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
